### ISSUE TITLE
Error creating database user

### ISSUE THREAD

**Issue by lawnmowerlatte** [jaywink/ansible-diaspora#7]
I'm running into trouble on a brand new Ubuntu 14.04 host. 

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_gyJL_e/ansible_module_postgresql_user.py", line 784, in main
    db_connection = psycopg2.connect(**kw)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
OperationalError: FATAL:  Peer authentication failed for user "postgres"


fatal: [diaspora.lawnmowerlatte.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "conn_limit": null,
            "db": "",
            "encrypted": false,
            "expires": null,
            "fail_on_user": true,
            "login_host": "",
            "login_password": "",
            "login_unix_socket": "",
            "login_user": "postgres",
            "name": "diaspora",
            "no_password_changes": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": "5432",
            "priv": null,
            "role_attr_flags": "CREATEDB,LOGIN",
            "ssl_mode": "prefer",
            "ssl_rootcert": null,
            "state": "present",
            "user": "diaspora"
        }
    },
    "msg": "unable to connect to database: FATAL:  Peer authentication failed for user \"postgres\"\n"
}
```

I checked the host and it has a `postgres` user. Any ideas what I'm doing wrong?

**Comment by jaywink** [comment]
Hi! Sorry for the late resposne, easter holiday trip and lots of work deadlines.

Still having problems? I'm guessing the operation isn't really executing the `become_user: postgres` correctly, this matches issue [here](https://github.com/ansible/ansible/issues/28433).

Do you have somewhere a different global `ansible_become_user` which is overriding this?

Personally I set the following in my playbook which are overridden by the tasks correctly:

    become: yes
    become_user: root
